### Logistic regression, example 1, Social Network Ads -data (classification)

In [30]:
# usual imports in classic ML pipeline for Classification
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

# we need ADDITIONAL metrics ONLY for classification
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import roc_auc_score

In [31]:
# load the data
df = pd.read_csv("Social_Network_Ads.csv")

# let's study the data
df

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

### Preliminary checks (duplicates, remove unneeded variables etc.)

In [32]:
# check duplicates
df.duplicated().sum()

np.int64(0)

In [33]:
# USER id is an identifier, drop it
df = df.drop("User ID", axis=1)

In [34]:
# double-check whether Gender-column is binary (exactly two options) or nominal (over 2 options)
df['Gender'].value_counts()

Gender
Female    204
Male      196
Name: count, dtype: int64

### Step 2: handle categoricals

We only have one binary variable, so we don't need to process other types of categoricals.

In [35]:
# this just converts the value of column to 0 or 1
# factorize in pandas works too, but only one column at a time
from sklearn.preprocessing import LabelEncoder
variables = ['Gender']
encoder = LabelEncoder()
df[variables] = df[variables].apply(encoder.fit_transform)

In [36]:
df

     Gender  Age  EstimatedSalary  Purchased
0         1   19            19000          0
1         1   35            20000          0
2         0   26            43000          0
3         0   27            57000          0
4         1   19            76000          0
..      ...  ...              ...        ...
395       0   46            41000          1
396       1   51            23000          1
397       0   50            20000          1
398       1   36            33000          0
399       0   49            36000          1

[400 rows x 4 columns]

### STEP 3: X/y and train/test -split

In [37]:
# first step, we split our data into SUPPORT variables and the TARGET variable
# X => support variables, y => target variable

# X => list of support variables that the model uses
# while predicting the target variable with the model
X = df.drop("Purchased", axis=1)

# our target variable y
y = df['Purchased']

In [38]:
# secondly, train/test -split with scikit-learn's helper function
# 0.3 for testing => 30% of the data is reserved for testing purposes (used for metrics later)
# and based on that => it's deduced that 70% will be in the training data

# you can also define the random state, which is sometimes useful
# if you want to "lock down" all the randomness in this part to get same results every time
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

### NOTE! one difference when compared to previous exercise (linear regression), WE NEED TO SCALE OUR SUPPORT VARIABLES FOR LOGISTIC REGRESSION!

In [39]:
# initialize the scaler and process the X-values!
# IN MOST CASES you can experiment with StandardScaler and MinMaxScaler
# BUT ONLY USE ONE SCALER AT A TIME FOR SUPPORT VARITABLES
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

# FIT the scaler ONLY to X-training data
# and ONLY transform the test data with that
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [40]:
# you can inspect how the original values have now
# switched to the scaled ones
# X_train